# Generated by Django 6.0.3 on 2026-04-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_globalsetting_studentadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('Notes', 'Notes'), ('Video', 'Video')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_notes/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('11th', '11th'), ('12th', '12th'), ('Degree', 'Degree'), ('Diploma', 'Diploma')], max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
