# Generated by Django 6.0.3 on 2026-04-10 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_coursecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education.category'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='education.category'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('branch', 'category', 'name')},
        ),
    ]
