# Generated by Django 6.0.3 on 2026-04-10 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_subject_category_alter_branch_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='category',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education.category'),
            preserve_default=False,
        ),
    ]
