# Generated by Django 6.0.3 on 2026-04-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_remove_branch_category_alter_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='education.category')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education.year'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('branch', 'category', 'year', 'name')},
        ),
    ]
