# Generated by Django 6.0.3 on 2026-04-17 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_year_alter_subject_unique_together_subject_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentadmission',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='education.year'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='education.branch'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='education.category'),
        ),
    ]
