# Generated by Django 6.0.3 on 2026-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_rename_name_studentadmission_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='education.subject'),
        ),
    ]
