# Generated by Django 6.0.3 on 2026-04-17 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_studentadmission_subjects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='year',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='year',
            name='branch',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='education.branch'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='year',
            unique_together={('category', 'branch', 'name')},
        ),
    ]
