# Generated by Django 6.0.3 on 2026-04-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_year_unique_together_year_branch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='year',
            unique_together={('category', 'name')},
        ),
        migrations.RemoveField(
            model_name='year',
            name='branch',
        ),
    ]

