# Generated by Django 6.0.3 on 2026-04-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_year_unique_together_remove_year_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='subject',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='education.subject')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.AddField(
            model_name='content',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='education.chapter'),
        ),
    ]
