# Generated by Django 6.0.3 on 2026-05-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_url',
            field=models.URLField(blank=True, help_text='Link to external storage (Google Drive, Cloudinary, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a file or provide a URL below', null=True, upload_to='notes/'),
        ),
    ]
