# Generated by Django 6.0.3 on 2026-05-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_content_file_url_alter_content_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='file',
        ),
        migrations.RemoveField(
            model_name='note',
            name='file_url',
        ),
        migrations.AddField(
            model_name='note',
            name='drive_link',
            field=models.URLField(default='', help_text='Google Drive PDF Link'),
        ),
    ]
