# Generated by Django 6.0.3 on 2026-05-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0019_remove_note_file_remove_note_file_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(help_text='Upload student photo', upload_to='top_students/')),
                ('course', models.CharField(help_text='Course Name (e.g. Diploma, Degree, 11th)', max_length=200)),
                ('department', models.CharField(help_text='Department/Stream (e.g. Mechanical, Computer, Science)', max_length=200)),
                ('subject', models.CharField(help_text='Subject Name (e.g. Mathematics, Physics)', max_length=200)),
                ('score_obtained', models.PositiveIntegerField(help_text='Marks obtained by student')),
                ('total_marks', models.PositiveIntegerField(help_text='Total marks for the subject')),
                ('achievement', models.CharField(blank=True, help_text='Specific achievement or rank (e.g. Class Topper, Gold Medalist)', max_length=250, null=True)),
                ('academic_year', models.CharField(help_text='Academic Year (e.g. 2025-2026)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Top Student',
                'verbose_name_plural': 'Top Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
