# Generated by Django 6.0.3 on 2026-07-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_topstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_records', to='education.content')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_videos', to='education.studentadmission')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_records', to='education.video')),
            ],
            options={
                'verbose_name': 'Watched Video',
                'verbose_name_plural': 'Watched Videos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('content__isnull', False)), fields=('student', 'content'), name='unique_student_content_watch'), models.UniqueConstraint(condition=models.Q(('video__isnull', False)), fields=('student', 'video'), name='unique_student_video_watch')],
            },
        ),
    ]
