# Generated by Django 6.0.3 on 2026-07-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_watchedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='account_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Graduated', 'Graduated')], default='Active', max_length=20),
        ),
    ]
